### ISSUE TITLE
Scope of this list

### ISSUE THREAD

**Issue by highb** [terrytangyuan/awesome-argo#44]
Hi! Thanks for creating this repo, I've found it very useful for getting an overview of and navigating the Argo ecosystem!

I have a project that I've started called [kustomize-everything](https://github.com/kustomize-everything) which aims to provide opinionated workflows around using Kustomize to build your environments and deploy them in an entirely declarative way. It's not directly related to Argo by itself, but I do use Argo to deploy the k8s manifests that it builds. Do you think that tools of this nature that are generating the configuration that Argo then handles the deployment of would be a good addition to this list or should I find another place to add them? I am considering creating my own `kustomize-everything/awesome-kustomize` list to start collecting some of the cool tools in that ecosystem, but I figured I would ask if you'd like me to contribute here first.

**Comment by terrytangyuan** [comment]
Thank you! That looks like a great project but I'd like to see more traction/adoption from the community before adding it to the list. Keep up the good work!

**Comment by highb** [comment]
That makes sense. I'll go ahead and close this.
