### ISSUE TITLE
I have a Chinese guide of Argo workflows

### ISSUE THREAD

**Issue by LinuxSuRen** [terrytangyuan/awesome-argo#50]
As I mentioned in the title, I'm not sure if it's good  to place it in this repo.

See also https://github.com/LinuxSuRen/argo-workflows-guide

**Comment by terrytangyuan** [comment]
Thanks. Looks like it's still in progress. Feel free to submit a PR once it's ready.

**Comment by LinuxSuRen** [comment]
I'll update it continuously. So, there is no ready state.

**Comment by terrytangyuan** [comment]
Sure feel free to send a PR

**Comment by LinuxSuRen** [comment]
Is that ok to put it in the `Blog Posts` list? Or any suggestions about the category.

**Comment by terrytangyuan** [comment]
That should be fine for now. We'll probably want to come up with new categories later.
